mvp
profcomff/marketing-backend pull request #2
Opened 2022-08-23 07:54 UTC by mixx3

2022-08-23 09:30 UTC, semen603089 commented on engine/routes/models.py
> +            raise ActionError(v)
Обычно при ошибках валидации в pydantic кидают ValueError/ValidationError

2022-08-23 09:30 UTC, semen603089 commented on engine/methods/db_utils.py
> +        path_to=user_info.path_to)
Интересно, а здесь не работает **user_info.dict()?

2022-08-23 09:40 UTC, dyakovri commented on engine/routes/models.py
> +            raise ActionError(v)
Именно ValueError, который вызовет автоматический ValidationError от pydantic. Этим стоит пользоваться

2022-08-23 09:41 UTC, semen603089 commented
Файлы .jinja это для копира. Ты видимо копировал репку руками, поэтому они остались, они должны были переформатироваться. Их нужно либо удалить и вставить нашу лицензию какую нибудь(см. любую репку), либо что то то ещё. Но их так оставлять не надо.

2022-08-23 09:43 UTC, semen603089 commented
С ридми ситуация та же, стоит тогда ручками написать норм ридми небольшой

2022-08-23 09:45 UTC, semen603089 commented
Файлы .copier надо удалить, они тоже не нужны

2022-08-23 09:54 UTC, dyakovri requested changes
Давай проект назовем marketing_api и все данные перенесем туда
В корне должны остаться 
```
|
|- marketing_api  – папка с исходным кодом, сюда перенести все исполняемые файлы
|- .github – папка с кодом для GH Actions
# Описание проекта
|- README.md
|- LICENCE
# Сборка
|- Dockerfile
|- flake8.conf
|- gunicorn_conf.py
|- requirements.txt
|- alembic.ini  # в этом файле хранятся данные для создания автоматических миграций базы данных
|- migrations  # в этой папке хранятся конфигурация миграций и сами миграции
# Настройки проекта
|- pyproject.toml
```

2022-08-23 09:54 UTC, dyakovri commented on .github/workflows/build_and_publish.yml
> +      CONTAITER_NAME: com_profcomff_ui_timetable_test
Поменяй на com_profcomff_api_marketing_test

2022-08-23 09:54 UTC, dyakovri commented on .github/workflows/build_and_publish.yml
> +      url: https://timetable.ui.test.profcomff.com/
https://marketing.api.test.profcomff.com/

2022-08-23 09:54 UTC, dyakovri commented on LICENSE.jinja
> +Copyright (c) {{ copyright_date }} {{ author_fullname }}
Кажется твой шаблон что-то недогенерировал @semen603089

2022-08-23 09:54 UTC, dyakovri commented on Dockerfile
> +ENTRYPOINT [ "gunicorn", "-k", "uvicorn.workers.UvicornWorker", "-c", "/app/gunicorn_conf.py", "calendar_backend.routes.base:app" ]
`calendar_backend.routes.base:app`??

2022-08-23 09:54 UTC, dyakovri commented on README.md.jinja
> +- Add yours!
Кажется твой шаблон что-то недогенерировал @semen603089

2022-08-23 09:54 UTC, dyakovri commented on copier.yml
> +# https://copier.readthedocs.io/en/stable/configuring/
Ненужный файл

2022-08-23 09:54 UTC, dyakovri commented on engine/routes/action.py
> +        print("error with db")
Лучше логику обработки ошибки с БД унести в функцию

2022-08-23 09:54 UTC, dyakovri commented on engine/routes/action.py
> +        print("error with db")
Либо целиком все перенести сюда

2022-08-23 09:54 UTC, dyakovri commented on engine/routes/action.py
> +        print("error with db")
А еще кажется, что в таком случае пользователь ничего не получит

2022-08-23 09:54 UTC, dyakovri commented on engine/settings.py
> +        env_file = "../.env"
Просто ".env"
И запускать надо из папки проекта, а не из папки с исходным кодом

2022-08-23 09:54 UTC, dyakovri commented on migrations/env.py
> +from calendar_backend.settings import get_settings
`calendar_backend`?

2022-08-23 09:55 UTC, dyakovri commented
Файл .gitignore не вижу

2022-08-23 09:58 UTC, semen603089 commented on LICENSE.jinja
> +Copyright (c) {{ copyright_date }} {{ author_fullname }}
Так там надо команды запускать просто отдельно))

2022-08-23 10:01 UTC, grigoriev-semyon commented
Ещё там есть файлы __init__.py
Они там нагненерены не с проста)) 
Туда нужно важные импорты кидать 
Посмотри наш с тобой бэк по календарю

2022-08-26 16:20 UTC, dyakovri reviewed
Я все-таки за то, чтобы переименовать engine в marketing_backend

2022-08-26 16:20 UTC, dyakovri commented on engine/routes/models.py
> +            raise ValueError(f"Invalid action {value}")
Вообще Enum умеет сам проверяться 
Но сейчас предлагаю оставить любую строку

2022-08-26 16:20 UTC, dyakovri commented on engine/routes/action.py
> +@action_router.post('/v1/post')
Давай action назовем 
/v1/action

2022-08-26 16:20 UTC, dyakovri commented on engine/methods/db_utils.py
> +def add_action_from_user_info(user_info: ActionInfo,
Так может пусть будет action_info, не user? 
И давай эту функцию целиком перенесем в ручку, а от файла избавимся

2022-08-26 16:20 UTC, dyakovri commented on engine/exceptions.py
> +class DB_Error(Exception):
Лучше DbError
А она точно нужна? Просто SqlAchemyError использовать не подойдет?

2022-08-26 16:24 UTC, semen603089 commented on engine/routes/models.py
> +            raise ValueError(f"Invalid action {value}")
@mixx3 он тут вообще умрет 
Actions is not Itarable

2022-08-26 20:52 UTC, dyakovri commented on Dockerfile
> +ENTRYPOINT [ "gunicorn", "-k", "uvicorn.workers.UvicornWorker", "-c", "/app/gunicorn_conf.py", "engine.routes.base:app" ]
engine -> marketing

2022-08-26 20:53 UTC, dyakovri commented on marketing_api/routes/action.py
> +from ..models.db import ActionsInfo
Ни нада `..`!!!

2022-08-26 20:53 UTC, dyakovri commented on marketing_api/routes/base.py
> +from ..settings import get_settings
Ни нада `..`!!!

2022-08-26 20:54 UTC, dyakovri requested changes

2022-08-26 20:54 UTC, dyakovri commented on marketing_api/settings.py
> +    API_URL: AnyHttpUrl = "http://127.0.0.1:8000"
Зачем?

2022-08-26 21:36 UTC, dyakovri approved these changes

2022-08-26 21:37 UTC, merged