enhancement
profcomff/marketing-backend pull request #5
Opened 2022-09-07 14:29 UTC by mixx3

union number should be nullable? integer?

2022-09-07 14:37 UTC, dyakovri commented on marketing_api/routes/models.py
> +    user_id: int | None
А Foreign key может быть Null в БД?

2022-09-07 14:37 UTC, dyakovri commented on marketing_api/routes/models.py
> +    union_number: int | None
При запуске приложения мы не знаем union_number, он тут всегда None будет
Надо сделать ручку patch user, которая будет по user_id добавлять union_number

2022-09-07 14:37 UTC, dyakovri commented on marketing_api/models/db.py
> +    create_ts = Column(sqlalchemy.DateTime, nullable=False, default=datetime.utcnow)
Давай сюда еще `modify_ts = Column(DateTime, nullable=False, default=datetime.utcnow, onupdate=datetime.utcnow)`

2022-09-07 14:37 UTC, dyakovri commented on marketing_api/routes/models.py
> +    user_id: int | None
Это вопрос, я правда не знаю, сработает ли

2022-09-07 14:38 UTC, dyakovri commented
Еще надо сгенерировать миграции alembic 
Это делается командой `alembic revision --autogenerate -m "Название изменения в БД"`
Это создаст файл для автоматического обновления базы данных при раскатке

2022-09-08 17:00 UTC, mixx3 commented
готово

2022-09-09 12:05 UTC, semen603089 requested changes

2022-09-09 12:05 UTC, grigoriev-semyon commented on marketing_api/routes/base.py
> +    else:
Здесь стоит убрать else
оно и так после ошибки вылетит

2022-09-09 12:05 UTC, semen603089 commented on tests/test_post.py
> +if __name__ == "__main__":
это здесь зачем...

2022-09-09 12:05 UTC, semen603089 commented on marketing_api/routes/base.py
> +async def http_validation_error_handler(req, exc):
лучше поменять 500 на что то более подходящее мб 422

2022-09-09 12:05 UTC, semen603089 commented on marketing_api/models/db.py
>      id = Column(sqlalchemy.Integer, primary_key=True)
добавь сюда repr() пж

2022-09-10 08:30 UTC, semen603089 approved these changes

2022-09-10 09:28 UTC, dyakovri requested changes

2022-09-10 09:28 UTC, dyakovri commented on marketing_api/models/db.py
> +    union_number = Column(sqlalchemy.Integer, nullable=True)
Давай все-таки строку

2022-09-10 09:28 UTC, dyakovri commented on marketing_api/routes/base.py
> +async def patch_user(id: int, union_number: int):
Почему в патч параметры передаются как GET параметры, а не как json?
Чтобы передать как json надо создать схему

2022-09-10 09:28 UTC, dyakovri commented on marketing_api/routes/base.py
> +async def patch_user(id: int, union_number: int):
GET параметры можно делать только в GET запросах (ну формально они поддерживаются во всех браузерах, но это не соответствует спецификации протокола HTTP)

2022-09-10 10:28 UTC, dyakovri approved these changes

2022-09-10 10:30 UTC, dyakovri requested changes

2022-09-10 10:30 UTC, dyakovri commented on marketing_api/routes/base.py
> +async def patch_user(patched_user: User):
Погоди, а куда id из пути делся?

2022-09-10 10:30 UTC, dyakovri commented on marketing_api/routes/base.py
> +async def patch_user(patched_user: User):
Он же запятисотит при запросе

2022-09-10 10:30 UTC, dyakovri commented on marketing_api/routes/base.py
> +async def patch_user(patched_user: User):
Обычно тут делают отдельную схему UserPatch

2022-09-10 10:31 UTC, dyakovri commented on tests/test_post.py
> +    user = User(**db_user.json())
Тут я бы не стал модельки вообще использовать
Ручками формировал json

2022-09-24 15:56 UTC, mixx3 commented on marketing_api/routes/base.py
> +async def patch_user(patched_user: User):
ну тесты проходит) Отдельную модель patched_user хз делать или нет, там 1 поле только будет тогда (union number)

2022-09-24 16:00 UTC, dyakovri commented on marketing_api/routes/base.py
> +async def patch_user(patched_user: User):
Да, одно поле, и это нормально

2022-09-24 16:36 UTC, dyakovri approved these changes

2022-09-24 16:42 UTC, merged